### ISSUE TITLE
Question on SPI interface

### ISSUE THREAD

**Issue by capiman2** [drandreas/tpm-tis-spi#1]
Hi,

no real bug report, but I have not found another way to get in contact with you.

On
https://github.com/drandreas/tpm-tis-spi
there is a nice picture on the SPI interface.
I am just trying to connect a TPM to a uC. As first command I have chosen TPM_CC_STARTUP, I hope this is correct.
I sent the 12 (=10 + 2) bytes via SPI to TPM and also can see them on my connected Logic Analyzer.
Before I pull CS to low.

Now how and when to receive the answer? Just send (10? 8?) further dummy bytes, so instead of sending 12 I send 20 bytes?
When sending byte by byte I received byte by byte (normal via SPI). Shall there be the answer already inside (after 10 sent bytes)?

As I learned it is essential that CS is left untouched, so it must stay low. But after the request it must go high?
Or can it stay low?

Is PIRQ of TPM needed for simple receiving? If not, when it is needed?

Many thanks!

Best regards,

Marie

**Comment by drandreas** [comment]
I assume you are trying to implement a TPM driver from scratch - Instead of using an existing one like mine. I'm also assuming that you are targeting an TPM 2.0.

The TPM Interface Specification (TIS) is layered (almost like a network stack).
First you have a definition of how to READ and WRITE 1-n bytes. This is where I had to tweak the CS handling.
See [TCG PC Client Platform TPM Profile (PTP) Specification](https://trustedcomputinggroup.org/resource/pc-client-platform-tpm-profile-ptp-specification/), Capture 7.4.5 Flow Control for details. 

After you've managed basic flow control, you have to implement the memory mapped IO of all the TPM "registers".
Note: I'm using the term memory mapped IO, since on a PC, the mapping is usually implemented in the Platform Control Hub (PCH) and the CPU does not have to handle the low level SPI protocol.

Now you can use the "memory mapped" registers to talk to the TPMs state machine and also execute commands as specified in [TPM 2.0 Library Specification for details](https://trustedcomputinggroup.org/resource/tpm-library-specification/). At this interface level one of the “registers" functions as a FIFO where you can send commands like TPM_CC_STARTUP too. But you also have to access the other registers to initiate the processing and wait for the completion.

**Comment by drandreas** [comment]
closed due to inactivity
